const io = require('socket.io-client');
const URL = 'http://localhost:3000';
const sleep = ms => new Promise(r => setTimeout(r, ms));
const get = s => new Promise(r => s.emit('getState', r));
const emit = (s, ev, ...a) => new Promise(r => s.emit(ev, ...a, r));
(async () => {
  const host = io(URL);
  const code = await emit(host, 'create', { name: 'H' });
  console.log('room', code.code);
  const others = [];
  for (let i = 0; i < 3; i++) others.push(io(URL));
  for (let i = 0; i < 3; i++) console.log('join P' + i, await emit(others[i], 'join', { code: code.code, name: 'P' + i }));
  console.log('non-host settings blocked:', await emit(others[0], 'settings', { rounds: 2 }));
  console.log('set settings:', await emit(host, 'settings', { rounds: 2, speechTime: 60, discussTime: 60 }));
  host.emit('ready'); others.forEach(c => c.emit('ready'));
  await sleep(300);
  console.log('start:', await emit(host, 'start'));
  let st = await get(host);
  console.log('phase:', st.phase, '| scenario:', st.scenario?.title || 'NONE');
  host.emit('startRound'); await sleep(300);
  st = await get(host);
  const spName = st.players.find(p => p.id === st.speakerId)?.name;
  console.log('phase:', st.phase, '| speaker:', spName);
  console.log('vote in speech blocked:', await emit(host, 'vote', st.players.find(p => p.id !== st.meId && p.alive).id));
  console.log('non-turn reveal blocked:', await emit(others[0], 'reveal', 'profession'));
  const all = [host, ...others]; all.forEach((c, i) => c._name = i === 0 ? 'H' : 'P' + (i - 1));
  const ssock = all.find(c => c._name === spName);
  console.log('reveal by speaker:', await emit(ssock, 'reveal', 'profession'));
  for (let i = 0; i < 4; i++) { host.emit('endSpeech'); await sleep(250); }
  st = await get(host);
  console.log('after 4 endSpeech phase:', st.phase);
  host.emit('forceVote'); await sleep(300);
  st = await get(host);
  console.log('phase:', st.phase);
  const target = st.players.find(p => p.alive && p.id !== st.meId);
  console.log('vote H:', await emit(host, 'vote', target.id));
  console.log('vote P0:', await emit(others[0], 'vote', target.id));
  host.emit('finishVote'); await sleep(300);
  st = await get(host);
  console.log('after vote phase:', st.phase, '| eliminated:', st.eliminationLog.at(-1)?.name, '| alive:', st.players.filter(p=>p.alive).length);
  console.log('ALL OK');
  process.exit(0);
})().catch(e => { console.error('FAIL', e.message || e); process.exit(1); });
